name: ttg-integration
services:
  ttg-server:
    container_name: ttg-integration-server
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      mc:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      API_URL: ${API_URL}
      CF_ACCOUNT_ID: ${CF_ACCOUNT_ID}
      CF_WORKERS_AI_API_TOKEN: ${CF_WORKERS_AI_API_TOKEN}
      CF_TEXT_GENERATION_MODEL: ${CF_TEXT_GENERATION_MODEL}
      CF_TEXT_TO_IMAGE_MODEL: ${CF_TEXT_TO_IMAGE_MODEL}
    env_file:
      - .env.compose
    init: true

  postgres:
    container_name: ttg-integration-postgres
    image: postgres:17.5-alpine3.22@sha256:fbe21607052bb5c298674f2fd8cf044a63aa3ddf50b81627f894f91f40f50bcb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.compose
    init: true

  minio:
    container_name: ttg-integration-minio
    image: minio/minio@sha256:a616cd8f37758b0296db62cc9e6af05a074e844cc7b5c0a0e62176d73828d440
    command: server /data
    ports:
      # The minio API endpoint
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.compose
    init: true

  mc:
    container_name: ttg-integration-minio-client
    image: minio/mc@sha256:09f93f534cde415d192bb6084dd0e0ddd1715fb602f8a922ad121fd2bf0f8b44
    depends_on:
      minio:
        condition: service_healthy
      # Create bucket if missing
    entrypoint: >
      /bin/sh -c " until (mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD && mc mb --region us-east-2 --ignore-existing local/ttg); do
        echo 'Waiting for MinIO to be ready...';
        sleep 5;
      done; "
    env_file:
      - .env.compose
