name: ttg
services:
  postgres:
    container_name: ttg-postgres
    image: postgres:17.5-alpine3.22@sha256:fbe21607052bb5c298674f2fd8cf044a63aa3ddf50b81627f894f91f40f50bcb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.compose
    init: true

  minio:
    container_name: ttg-minio
    image: minio/minio@sha256:a616cd8f37758b0296db62cc9e6af05a074e844cc7b5c0a0e62176d73828d440
    command: server --console-address ":9001" /data
    ports:
      # The minio API endpoint
      - "9000:9000"
      # The minio web console endpoint
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.compose
    init: true

  mc:
    container_name: ttg-minio-client
    image: minio/mc@sha256:09f93f534cde415d192bb6084dd0e0ddd1715fb602f8a922ad121fd2bf0f8b44
    depends_on:
      minio:
        condition: service_healthy
      # Create bucket if missing
    entrypoint: >
      /bin/sh -c " until (mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD && mc mb --region us-east-2 --ignore-existing local/ttg); do
        echo 'Waiting for MinIO to be ready...';
        sleep 5;
      done; "
    env_file:
      - .env.compose

volumes:
  postgres_data:
  minio_data:
